# To be run preferably in batch, without graphics:
# ./How-To-Geant4 run.mac
#This macro contains usefull gps-commands

#Set number of worker threads and initialize run
/run/numberOfThreads 4
/run/initialize

#Commands to use with the General Particle Source (GPS)
#/gps/particle proton     #beam particle
#/gps/particle neutron     #beam particle
/gps/particle deuteron     #beam particle
#/gps/particle gamma     #beam particle
/gps/position 0 0 -10 cm      #GPS position
/gps/direction 0 0 1     #oriented along the Z axis
/gps/ene/type Mono       #monoenergetic:   I=E
/gps/ene/mono 26.5 MeV   #sets energy for monoenergetic sources
/gps/pos/type Point 

/gps/pos/shape Circle    #the beam geometry is a circle
/gps/pos/radius 0. mm

#HISKP Cyclotron FWHM is approx 4mm. FWHM = 2.3548*sigma -> sigma = 1.79mm
/gps/pos/sigma_r 1.79 mm
/gps/pos/type Beam


#Output Folder name TargetEnergyProjectile_EntranceDia_InnerDia_ExitDia_Rotation
/custom/ana/setOutFolder C26-5d_4_1_4_0

#Shielding thickness (default 20cm)
/custom/geo/change_a 20 cm

#Entrance_Diameter (default 4cm)
/custom/geo/change_b 4 cm

#Inner_Diameter (choke) (default 2cm)
/custom/geo/change_c 1 cm

#Exit_Diameter (default 4cm)
/custom/geo/change_d 4 cm

#rotation (default 0. degree)
/custom/geo/change_e 0. degree

#Start a run and print progress in console
/run/printProgress 10000
/run/beamOn 10000000

#max value for beam On is 2.147.483.647 because this is the maximum value for a 32 bit integer
